apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    type: k44s
  name: test1.tests.oktawave
spec:
  group: tests.oktawave
  names:
    kind: test1
    listKind: test1list
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clientId:
              type: string
            namespace:
              pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
              type: string
            app1:
              type: list
            app2:
              type: list
          required:
          - namespace
          - clientId
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
